import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import { execSync } from "node:child_process";
import * as crypto from "node:crypto";

interface CsvRow {
  theme: string;
  text: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * RFC 4180 compliant CSV parser that handles newlines in quotes and escaped double quotes
 */
export function parseCSV(content: string): string[][] {
  const rows: string[][] = [];
  let currentRow: string[] = [];
  let currentVal = "";
  let insideQuotes = false;

  for (let i = 0; i < content.length; i++) {
    const c = content[i];
    if (insideQuotes) {
      if (c === '"' && content[i + 1] === '"') {
        currentVal += '"';
        i++;
      } else if (c === '"') {
        insideQuotes = false;
      } else {
        currentVal += c;
      }
    } else {
      if (c === '"') {
        insideQuotes = true;
      } else if (c === ",") {
        currentRow.push(currentVal);
        currentVal = "";
      } else if (c === "\n" || (c === "\r" && content[i + 1] === "\n")) {
        if (c === "\r") i++;
        currentRow.push(currentVal);
        if (currentRow.some((val) => val.trim().length > 0)) {
          rows.push(currentRow);
        }
        currentRow = [];
        currentVal = "";
      } else {
        currentVal += c;
      }
    }
  }

  if (currentRow.length > 0 || currentVal !== "") {
    currentRow.push(currentVal);
    if (currentRow.some((val) => val.trim().length > 0)) {
      rows.push(currentRow);
    }
  }

  return rows;
}

/**
 * Parses JST date string in format "YYYY/M/D H:m:s" or "YYYY/MM/DD HH:mm:ss" to UTC ISO string
 */
export function parseJstDateToIso(dateStr: string): string {
  const trimmed = dateStr.trim();
  // Match YYYY/M/D H:m:s
  const match = trimmed.match(/^(\d{4})\/(\d{1,2})\/(\d{1,2})\s+(\d{1,2}):(\d{1,2}):(\d{1,2})$/);
  if (!match) {
    // Fallback: try Date.parse
    const d = new Date(trimmed);
    if (isNaN(d.getTime())) {
      throw new Error(`Invalid date format: "${dateStr}"`);
    }
    return d.toISOString();
  }

  const year = parseInt(match[1], 10);
  const month = parseInt(match[2], 10) - 1;
  const day = parseInt(match[3], 10);
  const hour = parseInt(match[4], 10);
  const minute = parseInt(match[5], 10);
  const second = parseInt(match[6], 10);

  // Since original timestamps are in JST (UTC+9), convert to UTC
  // UTC hour = JST hour - 9
  const utcDate = new Date(Date.UTC(year, month, day, hour - 9, minute, second));
  return utcDate.toISOString();
}

/**
 * Escapes string for SQL literal: single quotes doubled
 */
function sqlEscape(val: string): string {
  return `'${val.replace(/'/g, "''")}'`;
}

export function generateMigrationSql(records: CsvRow[]): string {
  const sqlLines: string[] = [];
  sqlLines.push("-- Stockly Data Migration Script");
  sqlLines.push("-- Generated by scripts/import-csv.ts");
  sqlLines.push("PRAGMA foreign_keys = ON;");
  sqlLines.push("BEGIN TRANSACTION;");

  let tagCount = 0;

  for (const record of records) {
    const stockId = crypto.randomUUID();
    const contentSql = sqlEscape(record.text);
    const createdAtSql = sqlEscape(record.createdAt);
    const updatedAtSql = sqlEscape(record.updatedAt);

    sqlLines.push(
      `INSERT INTO stocks (id, content, image_keys, created_at, updated_at) VALUES ('${stockId}', ${contentSql}, NULL, ${createdAtSql}, ${updatedAtSql});`,
    );

    const theme = record.theme.trim();
    if (theme) {
      const tagId = crypto.randomUUID();
      const tagNameSql = sqlEscape(theme);
      sqlLines.push(
        `INSERT INTO tags (id, stock_id, name) VALUES ('${tagId}', '${stockId}', ${tagNameSql});`,
      );
      tagCount++;
    }
  }

  const scoreIncrement = records.length * 10;
  sqlLines.push(
    `UPDATE user_stats SET total_stocks = total_stocks + ${records.length}, score = score + ${scoreIncrement} WHERE id = 'default';`,
  );

  sqlLines.push("COMMIT;");
  return sqlLines.join("\n");
}

function printUsage() {
  console.log(`
Stockly CSV Import Utility
==========================
Usage:
  node --experimental-strip-types scripts/import-csv.ts [options]

Options:
  --file <path>     Path to CSV file (default: ignore/stock.csv)
  --dry-run         Validate and parse CSV without executing SQL
  --local           Execute migration against local D1 database
  --remote          Execute migration against remote production D1 database
  --db <name>       D1 database name (default: stockly-db for --local, stockly-db-prod for --remote)
  --sql-out <path>  Write generated SQL to a file
  -h, --help        Show this help message
`);
}

async function main() {
  // Auto-load .env from root or cwd if present
  const candidateEnvPaths = [
    path.resolve(process.cwd(), ".env"),
    path.resolve(process.cwd(), "../.env"),
  ];
  for (const envPath of candidateEnvPaths) {
    if (fs.existsSync(envPath)) {
      try {
        process.loadEnvFile(envPath);
        break;
      } catch {
        // Ignore parse errors
      }
    }
  }

  const args = process.argv.slice(2);
  let filePath = path.resolve(process.cwd(), "ignore/stock.csv");
  let isDryRun = false;
  let isLocal = false;
  let isRemote = false;
  let dbName = "";
  let sqlOutPath = "";

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === "-h" || arg === "--help") {
      printUsage();
      process.exit(0);
    } else if (arg === "--dry-run") {
      isDryRun = true;
    } else if (arg === "--local") {
      isLocal = true;
    } else if (arg === "--remote") {
      isRemote = true;
    } else if (arg === "--file" && i + 1 < args.length) {
      filePath = path.resolve(process.cwd(), args[++i]);
    } else if (arg === "--db" && i + 1 < args.length) {
      dbName = args[++i];
    } else if (arg === "--sql-out" && i + 1 < args.length) {
      sqlOutPath = path.resolve(process.cwd(), args[++i]);
    } else {
      console.error(`Unknown option: ${arg}`);
      printUsage();
      process.exit(1);
    }
  }

  if (!isDryRun && !isLocal && !isRemote && !sqlOutPath) {
    console.log("No execution target specified. Defaulting to --dry-run.");
    isDryRun = true;
  }

  if (!fs.existsSync(filePath)) {
    console.error(`Error: File not found: ${filePath}`);
    process.exit(1);
  }

  console.log(`Reading CSV file: ${filePath}`);
  const rawContent = fs.readFileSync(filePath, "utf-8");
  const rawRows = parseCSV(rawContent);

  if (rawRows.length < 2) {
    console.error("Error: CSV has no data rows (only header or empty).");
    process.exit(1);
  }

  const header = rawRows[0].map((h) => h.trim());
  const themeIdx = header.indexOf("テーマ");
  const textIdx = header.indexOf("テキスト");
  const createdIdx = header.indexOf("作成日");
  const updatedIdx = header.indexOf("更新日");

  if (textIdx === -1 || createdIdx === -1) {
    console.error("Error: CSV header must contain 'テキスト' and '作成日' columns.");
    console.error("Found header:", header);
    process.exit(1);
  }

  const validRecords: CsvRow[] = [];
  const errors: { row: number; error: string }[] = [];

  for (let i = 1; i < rawRows.length; i++) {
    const row = rawRows[i];
    const text = row[textIdx] ?? "";
    const theme = themeIdx !== -1 ? (row[themeIdx] ?? "") : "";
    const rawCreated = row[createdIdx] ?? "";
    const rawUpdated = updatedIdx !== -1 ? (row[updatedIdx] ?? rawCreated) : rawCreated;

    if (!text.trim()) {
      errors.push({ row: i + 1, error: "Empty text content" });
      continue;
    }

    try {
      const createdAtIso = parseJstDateToIso(rawCreated);
      const updatedAtIso = parseJstDateToIso(rawUpdated);
      validRecords.push({
        theme: theme.trim(),
        text: text,
        createdAt: createdAtIso,
        updatedAt: updatedAtIso,
      });
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      errors.push({ row: i + 1, error: msg });
    }
  }

  console.log("------------------------------------------");
  console.log(`Total CSV rows parsed: ${rawRows.length - 1}`);
  console.log(`Valid stock records:  ${validRecords.length}`);
  if (errors.length > 0) {
    console.log(`Skipped rows with errors: ${errors.length}`);
    for (const err of errors) {
      console.log(`  Row ${err.row}: ${err.error}`);
    }
  }

  if (validRecords.length > 0) {
    const timestamps = validRecords.map((r) => new Date(r.createdAt).getTime());
    const minDate = new Date(Math.min(...timestamps)).toISOString();
    const maxDate = new Date(Math.max(...timestamps)).toISOString();
    console.log(`Date range: ${minDate} ~ ${maxDate}`);
    const themesCount = validRecords.filter((r) => r.theme.length > 0).length;
    console.log(`Records with theme/tag: ${themesCount}`);
  }
  console.log("------------------------------------------");

  const migrationSql = generateMigrationSql(validRecords);

  if (sqlOutPath) {
    fs.writeFileSync(sqlOutPath, migrationSql, "utf-8");
    console.log(`Migration SQL written to: ${sqlOutPath}`);
  }

  if (isDryRun) {
    console.log("[Dry-run] Validation succeeded. No database modifications were performed.");
    return;
  }

  const targetDb = dbName || (isRemote ? "stockly-db-prod" : "stockly-db");
  const tempSqlFile = path.join(os.tmpdir(), `stockly_migration_${Date.now()}.sql`);
  fs.writeFileSync(tempSqlFile, migrationSql, "utf-8");

  try {
    const flag = isRemote ? "--remote" : "--local";
    console.log(`Executing migration on D1 database: ${targetDb} (${flag})...`);
    const cmd = `npx wrangler d1 execute ${targetDb} ${flag} --file "${tempSqlFile}"`;
    const output = execSync(cmd, {
      cwd: path.resolve(process.cwd(), "apps/api"),
      encoding: "utf-8",
      stdio: "pipe",
    });
    console.log("Migration executed successfully!");
    console.log(output);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error("Migration execution failed:", msg);
    process.exit(1);
  } finally {
    if (fs.existsSync(tempSqlFile)) {
      fs.unlinkSync(tempSqlFile);
    }
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    console.error("Fatal error:", err);
    process.exit(1);
  });
}
